(([
    (use_declaration)
    (self_parameter)
    (parameter)
    (generic_type)
    (dynamic_type)
    (line_comment)
    (attribute_item)
    (field_declaration)
    (enum_variant)
    (expression_statement)
    (match_arm)
    (generic_function)
    (macro_definition)
    (function_item)
    (function_signature_item)
    (struct_item)
    (enum_item)
    (impl_item)
] @_start @_end)
(#make-range! "parent" @_start @_end))
