vim.loader.enable(false)
local fixture = vim.fn.tempname()
assert(vim.fn.mkdir(fixture, "p") == 1)
local client = require("forge.client")
local function git(arguments)
  local result = vim.system(vim.list_extend({ "git", "-C", fixture }, arguments), { text = true, timeout = 10000 }):wait()
  assert(result.code == 0, result.stderr)
end
local function request(comparison, operation)
  local response, failure, completed
  client.request_host("repository.generate", { operation = operation or "generate", workspace = fixture, comparison = comparison,
    model = { provider = "fixture", model = "fixture" } }, function(result, error)
      response, failure, completed = result, error, true
    end)
  assert(vim.wait(10000, function() return completed end, 10), "generation host did not respond")
  return response, failure
end
local ok, failure = xpcall(function()
  git({ "init", "--quiet" })
  git({ "config", "user.name", "Forge Fixture" })
  git({ "config", "user.email", "forge@example.invalid" })
  vim.fn.writefile({ "before" }, fixture .. "/tracked.txt")
  git({ "add", "." })
  git({ "commit", "--quiet", "-m", "initial" })
  vim.fn.writefile({ "after" }, fixture .. "/tracked.txt")
  vim.fn.writefile({ "new" }, fixture .. "/untracked.txt")
  local result, error = request("head")
  assert(not result and error == "unsupported detached generation provider fixture", vim.inspect({ result, error }))
  result, error = request("staged")
  assert(not error and result.state == "none", vim.inspect({ result, error }))
  git({ "add", "tracked.txt" })
  result, error = request("staged")
  assert(not result and error == "unsupported detached generation provider fixture", vim.inspect({ result, error }))
  result, error = request("head", "fingerprint")
  assert(not result and error:find("unknown detached generation operation", 1, true), "obsolete fingerprint request remains supported")
end, debug.traceback)
client.stop()
assert(vim.wait(6000, function() return client._client.process == nil end, 20), "host did not stop")
vim.fn.delete(fixture, "rf")
assert(ok, failure)
print("native generation scope and removed fingerprint route OK")
