vim.loader.enable(false)
local editable = require("forge.editable")
local state = editable.new("document")
editable.register(state, "body", 7)
editable.register(state, "title", 0)
editable.record(state, "body", { "first" })
local captured = editable.capture_draft(state)
editable.record(state, "body", { "newer", "text" })
editable.saved_capture(state, captured)
assert(state.region.body.revision == 8 and state.region.body.pending)
assert(captured[1].text == "first", "new typing mutated an explicit capture")
editable.record(state, "title", { "Title" })
local body = editable.capture_draft(state, { body = true })
assert(#body == 1 and body[1].text == "newer\ntext" and body[1].base == 8)
editable.saved_capture(state, body)
assert(editable.suspend_generated_text(state), "saving one field cleared another field")
editable.saved_capture(state, editable.capture_draft(state))
assert(not editable.suspend_generated_text(state))
local before = vim.deepcopy(state)
assert(not pcall(editable.record, state, "body", { "bad\nrow" }))
assert(vim.deep_equal(before, state), "invalid text changed draft state")
local racing = editable.new("racing")
editable.register(racing, "body", 0)
for revision = 0, 999 do
  editable.record(racing, "body", { tostring(revision) })
  local original = editable.capture_draft(racing)
  for index = 1, 10 do
    editable.record(racing, "body", { tostring(revision), tostring(index) })
  end
  editable.saved_capture(racing, original)
  assert(editable.suspend_generated_text(racing))
  local latest = editable.capture_draft(racing)
  assert(latest[1].base == revision * 2 + 1)
  assert(latest[1].text == tostring(revision) .. "\n10")
  editable.saved_capture(racing, latest)
  assert(not editable.suspend_generated_text(racing))
end
print("editable capture ordering passed")
