vim.opt.runtimepath:prepend("nvim")
vim.loader.enable(false)
local root = vim.fn.getcwd()
local workspace, data = vim.fn.tempname(), vim.fn.tempname()
assert(vim.fn.mkdir(workspace, "p") == 1 and vim.fn.mkdir(data, "p") == 1)
local executable = require("forge.builder").binary_path()
local original_stdpath = vim.fn.stdpath
vim.fn.stdpath = function(kind) return (kind == "data" or kind == "config") and data or original_stdpath(kind) end
package.loaded["forge.builder"] = { ensure = function(callback)
  callback({ ok = true, path = executable })
  return function() end
end }
local client = require("forge.client")
client._set_launcher_for_test(vim.system)
local errors = {}
require("forge.infra.notifications").error = function(message) errors[#errors + 1] = message end
local state = require("forge.session").harness
local controller = require("forge.views.harness.controller")
local task = require("forge.views.harness.task")
local function latest_exchange()
  local snapshot, failure
  client.request("state.get", {}, function(result, problem) snapshot, failure = result, problem end)
  assert(vim.wait(5000, function() return snapshot or failure end, 10), "snapshot stalled")
  assert(not failure, failure)
  return snapshot.exchange[#snapshot.exchange]
end
local function wait_settled()
  assert(vim.wait(15000, function() return #errors > 0 or (not state.busy and not state.task_operation and not state.state_sync_pending) end, 10), "task did not settle")
  assert(#errors == 0, table.concat(errors, "\n"))
end
local success, failure = xpcall(function()
  vim.fn.chdir(workspace)
  require("forge").setup({ harness = { backend = "mock" } })
  require("forge").open_harness()
  assert(vim.wait(10000, function() return state.ready and state.session ~= nil end, 10), "Harness did not open")
  for _, selection in ipairs({ { "/fast", "fast" }, { "/ultrafast", "ultrafast" }, { "/ultrafast", "default" } }) do
    vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { selection[1] })
    controller.submit()
    assert(vim.wait(5000, function()
      return state.session.service_tier == selection[2] and not state.configuring and not state.configuration_debounce
    end, 10), "service-tier configuration did not settle: " .. selection[1])
    assert(not latest_exchange(), "service-tier command reached the model as a prompt")
  end
  vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { "/plan Demonstrate resumable task history" })
  controller.submit()
  wait_settled()
  local plan_task = assert(task.current(state))
  assert(plan_task.kind == "plan" and plan_task.status == "waiting", vim.inspect(plan_task))
  assert(state.session.execution_mode == "read")
  assert(vim.api.nvim_buf_get_lines(state.composer_buf, 0, -1, false)[1] == "", "admitted task did not clear composer")
  controller.set_mode("write")
  wait_settled()
  assert(task.current(state).status == "waiting", "permission change dismissed review wait")
  controller.task_transition({ action = "goal", text = "Exercise bounded goal continuation" })
  wait_settled()
  assert(task.current(state).kind == "goal")
  assert(state.session.execution_mode == "write", "new goal did not apply default write permission")
  assert(#state.task == 2)
  controller.task_transition({ action = "resume", task_id = plan_task.id })
  wait_settled()
  assert(task.current(state).id == plan_task.id and task.current(state).status == "waiting")
  assert(state.session.execution_mode == "write", "planning task lost saved permission")
  controller.task_transition({ action = "pause" })
  wait_settled()
  vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { "continue planning with the saved design" })
  controller.submit()
  wait_settled()
  assert(task.current(state).id == plan_task.id and task.current(state).status == "waiting")
  assert(state.session.active_plan_id == plan_task.plan_id, "message lost paused plan context")
  controller.task_transition({ action = "clear" })
  wait_settled()
  assert(not task.current(state), "clear retained current task")
  assert(#state.task == 2, "clear destroyed history")
  assert(vim.iter(state.task):any(function(entry) return entry.id == plan_task.id and entry.status == "cancelled" end))
  controller.task_transition({ action = "plan", text = "Execute a reviewed declaration design" })
  wait_settled()
  local executing_id = task.current(state).id
  controller.task_transition({ action = "execute", plan_id = "last" })
  wait_settled()
  assert(task.current(state).id == executing_id and task.current(state).kind == "execute",
    "acceptance did not preserve task identity")
  assert(task.current(state).status == "blocked" and task.current(state).phase == "implement",
    "read-only mock execution did not stop at its no-progress boundary: " .. vim.inspect(task.current(state)))
  assert(state.session.execution_mode == "write", "execute did not apply configured write permission")
  local tab_count, conversation = #vim.api.nvim_list_tabpages(), state.session.id
  vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { "/task new" })
  controller.submit()
  assert(require("forge.views.picker").is_open("harness-task"), "new task did not open the task picker")
  assert(#vim.api.nvim_list_tabpages() == tab_count and state.session.id == conversation, "new task changed the conversation")
  assert(task.current(state).id == executing_id, "opening new task picker detached execution")
  local new_picker = require("forge.views.picker")._state_for_test()
  new_picker.spec.on_confirm({ option = new_picker.spec.page_list[1].option_list[1] })
  require("forge.views.picker").close(true)
  vim.wait(20, function() return false end)
  assert(vim.api.nvim_get_current_buf() == state.composer_buf)
  assert(vim.api.nvim_buf_get_lines(state.composer_buf, 0, -1, false)[1] == "/plan ")
  vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { "" })
  controller.task_transition({ action = "resume" })
  wait_settled()
  local execution_resume = latest_exchange()
  assert(task.current(state).id == executing_id)
  assert(execution_resume.prompt == "" and execution_resume.lifecycle == "Execution resumed · implement", vim.inspect(execution_resume))
  assert(execution_resume.execution_id ~= nil, "control resume lost execution identity")
  local lifecycle_tree = require("forge.render.harness.interaction_tree").build({
    { kind = "exchange", exchange = execution_resume },
  })
  assert(lifecycle_tree.lines[1]:find("Execution resumed · implement", 1, true))
  assert(#lifecycle_tree.prompt_lines == 0, "control resume entered user prompt navigation")
  controller.task_transition({ action = "pause" })
  wait_settled()
  vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { "continue implementation using the accepted plan" })
  controller.submit()
  wait_settled()
  assert(task.current(state).id == executing_id and task.current(state).phase == "implement")
  local resumed = latest_exchange()
  assert(resumed.prompt == "continue implementation using the accepted plan")
  assert(resumed.lifecycle == nil or resumed.lifecycle == vim.NIL, "user message was replaced by a lifecycle label")
  assert(resumed.execution_id ~= nil, "resume became ordinary chat")
  controller.task_transition({ action = "goal", text = "Retain the goal across interruption" })
  wait_settled()
  local goal_task = task.current(state)
  controller.task_transition({ action = "resume" })
  wait_settled()
  local goal_resume = latest_exchange()
  assert(goal_resume.prompt == "" and goal_resume.lifecycle == "Goal resumed", vim.inspect(goal_resume))
  assert(goal_resume.goal_id == goal_task.goal_id, "control resume lost goal identity")
  controller.task_transition({ action = "pause" })
  wait_settled()
  vim.api.nvim_buf_set_lines(state.composer_buf, 0, -1, false, { "continue and preserve my instructions" })
  controller.submit()
  wait_settled()
  assert(task.current(state).id == goal_task.id)
  assert(latest_exchange().goal_id == goal_task.goal_id, "resume lost goal identity")
end, debug.traceback)
client.stop()
local collected = vim.wait(5000, function() return client._client.process == nil end, 10)
vim.fn.chdir(root)
vim.fn.stdpath = original_stdpath
assert(success and collected, failure or "Harness host was not collected")
print("harness_tasks_host: passed")
vim.cmd("qa!")
