vim.loader.enable(false)
local picker = require("forge.views.picker")
local input = require("forge.views.picker.input")
local search = require("forge.views.picker.search_input")
local popup = require("forge.infra.popup_window")
local origin = vim.api.nvim_get_current_win()
local previous = vim.api.nvim_get_current_buf()
vim.api.nvim_buf_set_name(previous, "picker-lock-origin")
vim.cmd("normal! m'")
vim.cmd("enew")
local host_buffer = vim.api.nvim_get_current_buf()
vim.api.nvim_buf_set_name(host_buffer, "picker-lock-host")
vim.keymap.set("n", ",", "<C-o>")
picker.open({ title = "Select Test", page_list = { {
  id = "test", option_list = { { label = "One" }, { label = "Two" } },
} } })
local active = picker._state_for_test()
local function assert_pinned(window, expected)
  vim.api.nvim_set_current_win(window)
  pcall(vim.cmd.normal, { args = { "," } })
  assert(vim.api.nvim_win_get_buf(window) == expected, "jump-back replaced a picker buffer")
  local changed = pcall(vim.cmd.buffer, previous)
  assert(not changed, "buffer command bypassed the picker lock")
  assert(vim.api.nvim_win_get_buf(window) == expected)
end
assert_pinned(active.win, active.buf)
assert(not vim.bo[active.buf].modifiable, "picker options became editable")
local input_buf, input_win = input.open(active.win, { input_start = 1 }, "draft", active.origin)
assert_pinned(input_win, input_buf)
vim.api.nvim_buf_set_lines(input_buf, 0, -1, false, { "edited draft" })
assert(input.text(input_buf) == "edited draft", "pinning disabled intended text input")
popup.close(input_win)
vim.wait(20, function() return false end)
local search_buf, search_win = search.open(active.win, { search_start = 1 }, "query", active.origin, function() end)
assert_pinned(search_win, search_buf)
vim.api.nvim_buf_set_lines(search_buf, 0, -1, false, { "filtered" })
assert(search.text(search_buf) == "filtered", "pinning disabled search editing")
popup.close(search_win)
vim.wait(20, function() return false end)
vim.api.nvim_set_current_win(active.win)
local close = vim.fn.maparg("q", "n", false, true)
close.callback()
vim.wait(20, function() return false end)
assert(not picker.is_open(), "picker close was blocked by the lock")
assert(vim.api.nvim_win_is_valid(origin) and vim.api.nvim_win_get_buf(origin) == host_buffer)
assert(not vim.wo[origin].winfixbuf, "picker lock leaked to the host")
vim.cmd.buffer(previous)
assert(vim.api.nvim_get_current_buf() == previous, "host buffer navigation remained locked")
print("picker_buffer_lock: passed")
