vim.opt.runtimepath:prepend("nvim")
local fixture = dofile("nvim/tests/forge/support/status_fixture.lua")
local status = require("forge.status")
local renderer = require("forge.status_render")
local dialogs = require("forge.views.status.dialogs")
local confirm = require("forge.infra.confirm")
local input_count, last_input = 0, nil
vim.ui.select = function() error("Legacy Forge interactions must not open a Snacks picker") end
vim.ui.input = function() error("Legacy Forge dialogs must not open a Snacks input") end
vim.notify = function() end
local function press(key)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, false, true), "xt", false)
end
status._set_runner_for_test(function(_, params, callback)
  if params.operation == "open" then
    local snapshot = fixture.snapshot(params.document)
    snapshot.file[2] = fixture.file("second.txt", 2)
    snapshot.section[1].file = { 1, 2 }
    callback(snapshot)
  elseif params.operation == "input" then
    input_count, last_input = input_count + 1, params
    callback(nil, "fixture captured mutation")
  elseif params.operation == "close" then callback({ closed = true })
  elseif params.operation == "close_view" then callback({})
  else error("Unexpected request " .. params.operation) end
end)
local state = status.open({ workspace = vim.fn.getcwd() })
assert(vim.wait(1000, function() return state.ready end))
local origin = vim.api.nvim_get_current_win()
for _, cancel in ipairs({ "n", "q", "<Esc>" }) do
  vim.api.nvim_win_set_cursor(origin, { 4, 0 })
  status.action(state, "discard", false)
  assert(vim.bo.filetype == "ForgeConfirm")
  assert(vim.deep_equal(vim.api.nvim_buf_get_lines(0, 0, -1, false), {
    "Discard ALL changes to file?", "  source.txt", "", "  [y] yes    [n] no",
  }))
  local geometry = vim.api.nvim_win_get_config(0)
  assert(geometry.relative == "editor" and geometry.height == 4)
  press(cancel)
  assert(vim.api.nvim_get_current_win() == origin and input_count == 0, "cancel changed Git state or lost the Status window")
end
vim.api.nvim_win_set_cursor(origin, { 4, 0 })
vim.cmd("normal! V2j")
status.action(state, "discard", true)
assert(vim.api.nvim_buf_get_lines(0, 0, 1, false)[1] == "Discard changes in 2 file(s)?")
assert(input_count == 0, "discard ran before confirmation")
press("y")
assert(vim.wait(1000, function() return input_count == 1 and not state.request_active end))
assert(vim.api.nvim_get_current_win() == origin and vim.fn.mode() == "n")
assert(last_input.selection.target[1].id == 1 and last_input.selection.target[2].id == 2)
assert(last_input.input.action == "discard")
state.replica.file[1].record.untracked = true
assert(dialogs.discard_message(state.replica, { location = { kind = "file", id = 1 } })[1] == "Delete untracked file?")
assert(dialogs.discard_message(state.replica, { location = { kind = "body", file = 1 } })[1] == "Discard this hunk?")
assert(dialogs.discard_message(state.replica, { location = { kind = "section", section = "unstaged" } })[1] == "Discard changes in 2 file(s)?")
local yes, no = 0, 0
local dialog = confirm.open({ "Cancel on leaving" }, function() yes = yes + 1 end, function() no = no + 1 end)
vim.api.nvim_set_current_win(origin)
assert(no == 1 and yes == 0 and not vim.api.nvim_buf_is_valid(dialog))
vim.api.nvim_win_set_cursor(origin, { 4, 0 })
status.action(state, "discard", false)
local stale_dialog = vim.api.nvim_get_current_buf()
local stale_confirm = vim.fn.maparg("y", "n", false, true).callback
status.close(state)
stale_confirm()
assert(input_count == 1, "closed Status accepted a retained confirmation")
assert(not vim.api.nvim_buf_is_valid(stale_dialog))
local branch_count, branch_name = 0, nil
local branch = dialogs.branch_name("feature/", function(value) branch_count, branch_name = branch_count + 1, value end)
assert(vim.bo[branch].filetype == "ForgeBranchPrompt")
assert(vim.api.nvim_win_get_config(0).height == 1)
assert(vim.api.nvim_buf_get_lines(branch, 0, -1, false)[1] == "feature/")
vim.api.nvim_buf_set_lines(branch, 0, -1, false, { "feature/parity" })
press("<CR>")
assert(branch_count == 1 and branch_name == "feature/parity" and vim.api.nvim_get_current_win() == origin)
dialogs.branch_name("feature/", function(value) assert(value == nil) branch_count = branch_count + 1 end)
press("q")
assert(branch_count == 2)
local replica = renderer.open("issues", {})
vim.api.nvim_buf_set_name(replica.buffer, "ForgeStatus://issues-test")
local snapshot = fixture.snapshot("issues", { context = { workspace = "fixture", branch = "main", recent = {}, issues = { 12 }, branch_prefix = "" } })
assert(renderer.apply_snapshot(replica, snapshot).kind == "Applied")
vim.api.nvim_win_set_buf(origin, replica.buffer)
local saved, complete
local editor = require("forge.views.status.issues_editor").attach(replica, function(text, callback) saved, complete = text, callback end)
local _, issue_row = replica.root:position("status:context:issues")
vim.api.nvim_win_set_cursor(origin, { issue_row + 1, 8 })
editor.sync()
assert(vim.bo[replica.buffer].modifiable)
vim.api.nvim_buf_set_lines(replica.buffer, issue_row, issue_row + 1, false, { "Issues: #12 #34" })
assert(replica.changedtick == vim.api.nvim_buf_get_changedtick(replica.buffer) and editor.dirty)
renderer.present_context(replica, { pr = { state = "none" }, about = { state = "ready", text = "new background message" } })
assert(replica.status == "Applied" and editor.dirty, "background About invalidated the Issues edit")
snapshot.revision = 1
assert(renderer.apply_snapshot(replica, snapshot).kind == "Applied")
assert(replica.block["status:context:issues"].text[1] == "Issues: #12 #34", "refresh overwrote the Issues draft")
vim.cmd("write")
assert(saved == "Issues: #12 #34")
complete(false)
assert(editor.dirty, "failed save discarded the Issues draft")
vim.cmd("write")
complete(true)
assert(not editor.dirty and not vim.bo[replica.buffer].modified)
vim.api.nvim_buf_set_lines(replica.buffer, issue_row, issue_row + 1, false, { "Issues: #56" })
editor.save()
vim.api.nvim_buf_set_lines(replica.buffer, issue_row, issue_row + 1, false, { "Issues: #78" })
complete(true)
assert(editor.dirty and editor.text == "Issues: #78", "save completion discarded a newer Issues edit")
local before_invalid = vim.api.nvim_buf_get_lines(replica.buffer, 0, -1, false)
vim.api.nvim_buf_set_lines(replica.buffer, issue_row, issue_row + 1, false, { "Issues: #78", "unwanted extra row" })
assert(vim.wait(1000, function() return not editor.repairing end))
assert(vim.deep_equal(vim.api.nvim_buf_get_lines(replica.buffer, 0, -1, false), before_invalid), "multi-line edit corrupted Status layout")
assert(replica.changedtick == vim.api.nvim_buf_get_changedtick(replica.buffer))
editor.save()
complete(true)
snapshot.context.issues = { 12, 34 }
snapshot.revision = 2
assert(renderer.apply_snapshot(replica, snapshot).kind == "Applied")
vim.api.nvim_win_set_cursor(origin, { 1, 0 })
editor.sync()
assert(not vim.bo[replica.buffer].modifiable, "non-Issues status rows became editable")
print("legacy popup presentation, cancellation, selection ownership, branch input and inline Issues passed")
vim.cmd("qa!")
