vim.loader.enable(false)
local render = require("forge.status_render")
local buffer = require("forge.buffer")
local fixture = dofile("nvim/tests/forge/support/status_fixture.lua")
local notices = {}
local replica = render.open("issues-projection", { notice = function(message) notices[#notices + 1] = message end })
vim.api.nvim_set_current_buf(replica.buffer)
local snapshot = fixture.snapshot(replica.document, { context = {
  workspace = "fixture", branch = "main", issues = {}, recent = {},
} })
assert(render.apply_snapshot(replica, snapshot).kind == "Applied")
local saved
local editor = require("forge.views.status.issues_editor").attach(replica, function(text, complete)
  saved = text
  complete(true)
end)
local _, row = replica.sequence:position("status:context:issues")
vim.api.nvim_win_set_cursor(0, { row + 1, 0 })
editor.sync()
vim.api.nvim_buf_set_lines(replica.buffer, row, row + 1, false, { "Issues: #42" })
assert(editor.dirty)
local count = vim.api.nvim_buf_line_count(replica.buffer)
vim.api.nvim_buf_set_lines(replica.buffer, row, row + 1, false, { "invalid", "extra line" })
assert(vim.wait(1000, function() return not editor.repairing end, 1))
assert(vim.api.nvim_buf_get_lines(replica.buffer, row, row + 1, false)[1] == "Issues: #42")
assert(vim.api.nvim_buf_line_count(replica.buffer) == count)
assert(#notices == 1)
assert(buffer.set_expansion(replica, "section:unstaged", false))
assert(buffer.set_expansion(replica, "section:unstaged", true))
assert(vim.api.nvim_buf_get_lines(replica.buffer, row, row + 1, false)[1] == "Issues: #42")
render.present_context(replica, replica.presentation)
assert(replica.status == "Applied")
assert(vim.api.nvim_buf_get_lines(replica.buffer, row, row + 1, false)[1] == "Issues: #42")
editor.save()
assert(saved == "Issues: #42" and not editor.dirty)
render.close(replica)
print("status Issues projection: accepted edit survives rejection, expansion, refresh, and save")
