return {
  -- {
  --   'Bekaboo/dropbar.nvim',
  --   keys = {
  --     {
  --       "<leader>fp",
  --       function()
  --         require("dropbar.api").pick()
  --       end,
  --       desc = "Dropbar pick"
  --     },
  --   },
  --   opts = {
  --     bar = {
  --       -- Disable all put path sources
  --       sources = function(buf, _)
  --         local sources = require('dropbar.sources')
  --         return { sources.path }
  --       end,
  --       enable = function(buf, win, _)
  --         -- print(vim.inspect(vim.bo[buf].ft))
  --         if
  --             not vim.api.nvim_buf_is_valid(buf)
  --             or not vim.api.nvim_win_is_valid(win)
  --             or vim.fn.win_gettype(win) ~= ''
  --             or vim.wo[win].winbar ~= ''
  --             or vim.bo[buf].ft == 'help'
  --             or vim.bo[buf].ft:find('snacks')
  --         then
  --           return false
  --         end
  --
  --         local stat = vim.uv.fs_stat(vim.api.nvim_buf_get_name(buf))
  --         if stat and stat.size > 1024 * 1024 then
  --           return false
  --         end
  --
  --         return vim.bo[buf].ft == 'markdown'
  --             or pcall(vim.treesitter.get_parser, buf)
  --             or not vim.tbl_isempty(vim.lsp.get_clients({
  --               bufnr = buf,
  --               method = 'textDocument/documentSymbol',
  --             }))
  --       end,
  --     }
  --   }
  -- }
}
