local key = require("../keys").key

return {
  -- {
  --   "kylechui/nvim-surround",
  --   version = "*", -- Use for stability; omit to use `main` branch for the latest features
  --   event = "VeryLazy", -- other results in key configs? C-g
  --   config = function()
  --     -- See defaults hereh
  --     -- <httpsh//github.com/kylechui/nvim-surround/blob/main/lua/nvim-surround/config.lua>
  --     require("nvim-surround").setup({
  --       keymaps = {
  --         insert = "<C-g>s",
  --         insert_line = "<C-g>S",
  --         -- normal = key("us"),
  --         normal = "S",
  --         -- normal_cur = key("uss"),
  --         normal_line = key("uS"),
  --         normal_cur_line = key("uSS"),
  --         visual = key("S"),
  --         visual_line = key("gS"),
  --         delete = nil, -- key("us"),
  --         change = key("cs"),
  --         change_line = key("cS"),    
  --       }, 
  --
  --     })
  --   end
  -- }
  -- {
  --   'echasnovski/mini.surround',  
  --   version = '*',
  --   config = function ()
  --     require("mini.surround").setup({
  --       -- Add custom surroundings to be used on top of builtin ones. For more
  --       -- information with examples, see `:h MiniSurround.config`.
  --       custom_surroundings = nil,
  --
  --       -- Duration (in ms) of highlight when calling `MiniSurround.highlight()`
  --       highlight_duration = 500,
  --
  --       -- Module mappings. Use `''` (empty string) to disable one.
  --       mappings = {
  --         add = "ls", -- Add surrounding in Normal and Visual modes
  --         delete = nil, -- Delete surrounding
  --         find = nil, -- Find surrounding (to the right)
  --         find_left = nil, -- Find surrounding (to the left)
  --         highlight = nil, -- Highlight surrounding
  --         replace = nil, -- Replace surrounding
  --         update_n_lines = nil, -- Update `n_lines`
  --
  --         suffix_last = nil, -- Suffix to search with "prev" method
  --         suffix_next = nil, -- Suffix to search with "next" method
  --       },
  --
  --       -- Number of lines within which surrounding is searched
  --       n_lines = 20,
  --
  --       -- Whether to respect selection type:
  --       -- - Place surroundings on separate lines in linewise mode.
  --       -- - Place surroundings on each line in blockwise mode.
  --       respect_selection_type = false,
  --
  --       -- How to search for surrounding (first inside current line, then inside
  --       -- neighborhood). One of 'cover', 'cover_or_next', 'cover_or_prev',
  --       -- 'cover_or_nearest', 'next', 'prev', 'nearest'. For more details,
  --       -- see `:h MiniSurround.config`.
  --       search_method = 'cover',
  --
  --       -- Whether to disable showing non-error feedback
  --       silent = false,
  --     }) 
  --   end
  -- }

}
