model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "pragmatic"

[features]
experimental_windows_sandbox = true
elevated_windows_sandbox = true
powershell_utf8 = true
steer = true
multi_agent = true

[projects.'\\?\D:\code\ferrous']
trust_level = "trusted"

[projects.'D:\']
trust_level = "trusted"

[projects.'\\?\D:\config']
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[mcp_servers.microsoft-learn]
type = "http"
url = "https://learn.microsoft.com/api/mcp"

[mcp_servers.docs-mcp]
type = "stdio"
command = "docs-mcp"
args = []

[mcp_servers.google-dev-knowledge]
type = "http"
url = "https://developerknowledge.googleapis.com/mcp"

[mcp_servers.google-dev-knowledge.env_http_headers]
"X-Goog-Api-Key" = "GOOGLE_DEV_KNOWLEDGE_MCP_KEY"

[mcp_servers.chrome-devtools]
type = "stdio"
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--channel=beta"]

[mcp_servers.github]
type = "stdio"
command = "github-mcp-server"
args = ["stdio", "--toolsets=context,actions,discussions,issues,labels,notifications,orgs,projects,pull_requests,repos,users"]

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = "GITHUB_AGENT_PERSONAL_ACCESS_TOKEN"

[mcp_servers.hf-mcp-server]
type = "http"
url = "https://huggingface.co/mcp?login"
